version: '3.9'

services:
  rpmbuilder:
    build:
      dockerfile: Dockerfile.redhat
    image: taylorm/rpmbuilder
  debbuilder:
    build:
      dockerfile: Dockerfile.debian
    image: taylorm/debbuilder
