version: '3.9'

services:
  rpmbuilder:
    command:
    - bash
    - -c
    - |
      ./make_react_webui_rpm.sh
      cd /dist
      /src/test.sh
    build: redhat
    image: reactrpm
    volumes:
    - ./redhat:/src
    - .:/dist
  debbuilder:
    command:
    - bash
    - -c 
    - |
      ./make_react_webui_deb.sh
      cd /dist
      /tmp/test.sh
    build: debian
    image: reactdeb
    volumes:
    - ./debian:/tmp/
    - .:/dist
